### ISSUE TITLE
!!! Installing wdio-wait-for package doesn't work anymore

### ISSUE THREAD

**Issue by tnacu-wb** [webdriverio/wdio-wait-for#103]
1. Run `rm -rf node_modules/; rm package-lock.json; npm i -D wdio-wait-for` .
2. Look in node_modules/wdio-wait-for folder.

These files are present only:
LICENSE
README.md
package.json

Please, fix this ASAP!

cc: @christian-bromann

**Comment by christian-bromann** [comment]
@elaichenkov I have a fix if you haven't already 😉

**Comment by elaichenkov** [comment]
Hey @christian-bromann 
That's cool. I'm trying to figure out what happens here.

Found quick fix:
```diff
- lib/src
+ lib
```
https://github.com/webdriverio/wdio-wait-for/blob/main/package.json#L8

**Comment by christian-bromann** [comment]
Please see https://github.com/webdriverio/wdio-wait-for/pull/104

**Comment by christian-bromann** [comment]
fyi: I understand your frustration but more `!!!` and `ASAP` usually don't help when it comes to these things 😉

**Comment by christian-bromann** [comment]
@tnacu-wb released a fix, please let us know if everything is back to normal.

**Comment by tnacu-wb** [comment]
@christian-bromann Thanks for fixing it! It works now. Sorry for lots of "!", I just wanted to highlight this issue. No frustration from my side. Cheers!
