### ISSUE TITLE
Logical `not` doesn't work with browser conditions

### ISSUE THREAD

**Issue by DmitryShashkov** [webdriverio/wdio-wait-for#175]
Hi! I am trying to use `not` together with `urlContains`, like this:
```
import { not, urlContains } from 'wdio-wait-for';
describe('Login page', () => {
  let page: LoginPage;

  beforeAll(async () => {
    page = new LoginPage();
  });

  // a couple of `it` statements skipped

  it('should log user in and redirect them to corresponding home page', async () => {
    const submitButton = page.getSubmitButton();
    await submitButton.click();

    await browser.waitUntil(not(urlContains('login')));
    await sleep(500);

    const urlAfterRedirects = await browser.getUrl();
    expect(urlAfterRedirects).toBe(`${browser.options.baseUrl}v3/library/my`);
  });
});
```

And get the following error:
```
Error: waitUntil condition failed with the following reason: Cannot read properties of undefined (reading 'getTitle')
```

In the [source code for urlContains](https://github.com/webdriverio/wdio-wait-for/blob/c475153aef02b4fe01693eddd5baf3bd082aef6f/src/browser/urlContains.ts#L15), it expects the context to be passed, which works if you don't wrap it:
```
 await browser.waitUntil(urlContains('login')); // this works correctly
```
but doesn't work when wrapped in `not`.

I believe the situation is the same for all combinations of logical + browser conditions.

**Comment by christian-bromann** [comment]
Hey @DmitryShashkov ,
thanks for filing the issue. This seems indeed like bug. We would appreciate any help on this so please help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) and reach out if you have any questions. Cheers!

**Comment by M-Hammad-Faisal** [comment]
@christian-bromann I am looking onto this issue.

**Comment by M-Hammad-Faisal** [comment]
@christian-bromann i found the issue. When I use wait until it acts like this.
```javascript
browser.waitUntil(urlContains("text")) => browser.waitUntil((this: WebdriverIO.Browser)=> {
                                           const url = await this.getUrl(); 
                                           ....
                                          })
```

but when i wrap it inside a function then, it becomes:
```javascript
browser.waitUntil(urlContains("text")) => browser.waitUntil(()=>{
                                           const condition = (this: WebdriverIO.Browser)=> {
                                             const url = await this.getUrl(); 
                                             ....
                                          }
)
```

Here `this` which is `WebdriverIO.Browser` gets lost as it gets nested in an arrow function.

`this` only works in functions made with `function` keyword. So, in an arrow function this is just `undefined`.

**Comment by christian-bromann** [comment]
Nice finding 👍  what would you suggest for a fix?

**Comment by M-Hammad-Faisal** [comment]
here are the two possible solutions:
one is that, i create logical functions with function keyword and bind the function with this word using func.call(this)
and other one is that rather than relying on `this` i directly use `browser.getUrl`. what do you suggest?

**Comment by M-Hammad-Faisal** [comment]
i believe later one would be nicer approach. we donot need to make code more complex and wonder where is `this` has gone. 😆

**Comment by christian-bromann** [comment]
Please go ahead and raise a PR with the approach you have in mind, I think it is better to make a final decision once there is some code.

**Comment by M-Hammad-Faisal** [comment]
@christian-bromann I found the first approach much shorter. 😄  have a look on this PR.
