### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by splurgeop** [webdriverio/wdio-wait-for#91]
I was just going thru this library and found that under the hood it uses the default wdio element locators only.
for example :

```ts
export function **visibilityOf**(selector: string): () => Promise<boolean> {
  return async (): Promise<boolean> => {
    const element = await $(selector);

    try {
      const isVisible = await element.isDisplayed();

      return isVisible;
    } catch {
      return false;
    }
  };
}
```

browser.visibility of uses isDisplayed() api of wdio.I am a bit confused on the use of this.
Why is this repo seperately published.
Please pardon my knowledge on this.I just wanted to clear my doubt

**Comment by christian-bromann** [comment]
> Why is this repo seperately published.

Technically we could move this into the main WebdriverIO repository and publish it alongside the core packages but given this project was originally contributed by the community we kept it as an individual repository. I am curious if you see a problem with that?

Or do I missunderstand the question?

**Comment by splurgeop** [comment]
Thanks for the information.
I was trying to use this package but i realised that it uses the same API under the hood while working with wdio.
With wdio can I use this package?

**Comment by splurgeop** [comment]
If i use this package in my wdio test and i use 
Browser.visibilityof function/API only to realise that I can instead use 
$(element).is displayed.
So was a bit confused on its usage with wdio

**Comment by christian-bromann** [comment]
> With wdio can I use this package?

Yes it is build to simplify assertions when using WebdriverIO. I will close the issue given that all confusions got clarified. Let me know if you have more questions.
